import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { SignInButton , useUser, SignOutButton} from "@clerk/nextjs";
import { api } from "~/utils/api";


const Home: NextPage = () => {
 
  const user = useUser();

  const {data} = api.posts.getAll.useQuery();
  return ( 
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      <div>
      {!user.isSignedIn && <SignInButton/>}
      {!!user.isSignedIn && <SignOutButton/>}
      
      </div>
      <div>
       { data?.map((post) => (
          <div key={post.id}>
            <h2>{post.content}</h2>
          </div>
       ))}  
          
      </div>
      </main>
    </>
  );
};

export default Home;
